## Final Project Submission

Please fill out:
* Student name:Christopher Noel 
* Student pace:Full time 
* Instructor name: Maryann Mwikali

### EDA (Exploratory Data Analysis)
This a process whereby we are to dissect our "data" by loading it into a data frame , this is done so as to enable us **understand the data , gain insights into the data structures, variable and basic properties**
But before we begin we will have to include some technical tools to help us ie{**libraries**}

#### Libraries 
(why do we need libraries)= They provide a wide range of tools and modules for various tasks making it easier to work on specific tasks
 **pandas as pd - data analysis & manipulation**
 **numpy as np - numerical computing**
 **matplotlib.pyplot as plt - creates static,interactive & animated visuals **
 **seaborn as sns - proides high level interface for drawing interactive statistical graphs**

In [1]:
#1ST Step in EDA= importing of necessary librarie
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [45]:
# 2ND Step in EDA =reading dataset
df = pd.read_csv("data/Aviation_Data.csv", low_memory=False)
df

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90343,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
90344,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
90346,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90347,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

### 3rd EDA=Analysing the data(data understanding)
In this part we will basically be basically looking at the basic features of our data set ie{**what is in the dataset,type of data(boolean/integer),no.of rows/columns}

In [3]:
# summary of the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        73659 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.4+ MB

In [4]:
#finding dimensions of the dataframe
df.shape

(90348, 31)

In [5]:
# finding the first(20) rows of the data frame
df.head(20)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
0,20001218X45444,Accident,SEA87LA080,1948-10-24,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,Cruise,Probable Cause,NaN
1,20001218X45447,Accident,LAX94LA336,1962-07-19,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,Unknown,Probable Cause,19-09-1996
2,20061025X01555,Accident,NYC07LA005,1974-08-30,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,Cruise,Probable Cause,26-02-2007
3,20001218X45448,Accident,LAX96LA321,1977-06-19,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,12-09-2000
4,20041105X01764,Accident,CHI79FA064,1979-08-02,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,0.0,VMC,Approach,Probable Cause,16-04-1980
5,20170710X52551,Accident,NYC79AA106,1979-09-17,"BOSTON, MA",United States,42.445277,-70.758333,NaN,NaN,...,NaN,Air Canada,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
6,20001218X45446,Accident,CHI81LA106,1981-08-01,"COTTON, MN",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,IMC,Unknown,Probable Cause,06-11-2001
7,20020909X01562,Accident,SEA82DA022,1982-01-01,"PULLMAN, WA",United States,NaN,NaN,NaN,BLACKBURN AG STRIP,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Takeoff,Probable Cause,01-01-1982
8,20020909X01561,Accident,NYC82DA015,1982-01-01,"EAST HANOVER, NJ",United States,NaN,NaN,N58,HANOVER,...,Business,NaN,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
9,20020909X01560,Accident,MIA82DA029,1982-01-01,"JACKSONVILLE, FL",United States,NaN,NaN,JAX,JACKSONVILLE INTL,...,Personal,NaN,0.0,0.0,3.0,0.0,IMC,Cruise,Probable Cause,01-01-1982
10,20020909X01559,Accident,FTW82DA034,1982-01-01,"HOBBS, NM",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Approach,Probable Cause,01-01-1982
11,20020909X01558,Accident,ATL82DKJ10,1982-01-01,"TUSKEGEE, AL",United States,NaN,NaN,NaN,TUSKEGEE,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Landing,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,"HOMER, LA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,"HEARNE, TX",United States,NaN,NaN,T72,HEARNE MUNICIPAL,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
14,20020917X02119,Accident,FTW82FPJ10,1982-01-02,"CHICKASHA, OK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
15,20020917X02117,Accident,FTW82FPG08,1982-01-02,"LITTLE ROCK, AR",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
16,20020917X01962,Accident,DEN82DTM08,1982-01-02,"MIDWAY, UT",United States,NaN,NaN,NaN,FIELD RANCH,...,Personal,NaN,0.0,0.0,0.0,1.0,IMC,Taxi,Probable Cause,02-01-1983
17,20020917X01656,Accident,ANC82FAG14,1982-01-02,"SKWENTA, AK",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,3.0,0.0,0.0,0.0,VMC,Unknown,Probable Cause,02-01-1983
18,20020917X02481,Accident,NYC82DA016,1982-01-02,"GALETON, PA",United States,NaN,NaN,5G6,CHERRY SPRINGS,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,Taxi,Probable Cause,02-01-1983
19,20020917X02339,Accident,MIA82DA028,1982-01-02,"MIAMI, FL",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,0.0,0.0,2.0,VMC,Cruise,Probable Cause,02-01-1983

In [6]:
# finding the last(20)rows of the data frame
df.tail(20)

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Location,Country,Latitude,Longitude,Airport.Code,Airport.Name,...,Purpose.of.flight,Air.carrier,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
90328,20221213106455,Accident,WPR23LA065,2022-12-13,"Lewistown, MT",United States,047257N,0109280W,KLWT,Lewiston Municipal Airport,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,14-12-2022
90329,20221215106461,Accident,ERA23LA089,2022-12-13,"Rockingham, NC",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,2.0,NaN,NaN,NaN,20-12-2022
90330,20221220106480,Accident,WPR23LA072,2022-12-13,"Liberal, KS",United States,NaN,NaN,NaN,NaN,...,NaN,Sierra Bravo Partnership,0.0,0.0,0.0,0.0,NaN,NaN,NaN,20-12-2022
90331,20221214106459,Accident,GAA23WA042,2022-12-14,"Happy Valley-Goose Bay, OF",Canada,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,2.0,0.0,NaN,NaN,NaN,20-12-2022
90332,20221215106463,Accident,ERA23LA090,2022-12-14,"San Juan, PR",United States,182724N,0066554W,SIG,FERNANDO LUIS RIBAS DOMINICCI,...,Personal,SKY WEST AVIATION INC TRUSTEE,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
90333,20221215106462,Accident,CEN23LA064,2022-12-15,"Patterson, LA",United States,NaN,NaN,NaN,NaN,...,NaN,ROTORCRAFT LEASING CO LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90334,20221219106474,Accident,ANC23LA009,2022-12-15,"Lihue, HI",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,1.0,1.0,0.0,NaN,NaN,NaN,22-12-2022
90335,20221219106475,Accident,WPR23LA069,2022-12-15,"Wichita, KS",United States,373829N,0972635W,ICT,WICHITA DWIGHT D EISENHOWER NT,...,NaN,NaN,0.0,0.0,0.0,1.0,NaN,NaN,NaN,19-12-2022
90336,20221219106470,Accident,ERA23LA091,2022-12-16,"Brooksville, FL",United States,282825N,0822719W,BKV,BROOKSVILLE-TAMPA BAY RGNL,...,Personal,GERBER RICHARD E,0.0,1.0,0.0,0.0,VMC,NaN,NaN,23-12-2022
90337,20221227106496,Accident,WPR23LA074,2022-12-17,"Cottonwood, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,27-12-2022
90338,20221219106472,Accident,DCA23LA096,2022-12-18,"Kahului, HI",United States,NaN,NaN,NaN,NaN,...,NaN,HAWAIIAN AIRLINES INC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90339,20221219106477,Accident,WPR23LA071,2022-12-18,"San Manual, AZ",United States,NaN,NaN,NaN,NaN,...,Personal,Chandler Air Service,0.0,0.0,0.0,3.0,NaN,NaN,NaN,20-12-2022
90340,20221221106483,Accident,CEN23LA067,2022-12-21,"Auburn Hills, MI",United States,NaN,NaN,NaN,NaN,...,Personal,Pilot,0.0,1.0,0.0,0.0,NaN,NaN,NaN,22-12-2022
90341,20221222106486,Accident,CEN23LA068,2022-12-21,"Reserve, LA",United States,NaN,NaN,NaN,NaN,...,Instructional,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,27-12-2022
90342,20221228106502,Accident,GAA23WA046,2022-12-22,"Brasnorte,",Brazil,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,0.0,0.0,0.0,NaN,NaN,NaN,28-12-2022
90343,20221227106491,Accident,ERA23LA093,2022-12-26,"Annapolis, MD",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,0.0,NaN,NaN,NaN,29-12-2022
90344,20221227106494,Accident,ERA23LA095,2022-12-26,"Hampton, NH",United States,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90345,20221227106497,Accident,WPR23LA075,2022-12-26,"Payson, AZ",United States,341525N,1112021W,PAN,PAYSON,...,Personal,NaN,0.0,0.0,0.0,1.0,VMC,NaN,NaN,27-12-2022
90346,20221227106498,Accident,WPR23LA076,2022-12-26,"Morgan, UT",United States,NaN,NaN,NaN,NaN,...,Personal,MC CESSNA 210N LLC,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
90347,20221230106513,Accident,ERA23LA097,2022-12-29,"Athens, GA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,0.0,1.0,0.0,1.0,NaN,NaN,NaN,30-12-2022

In [7]:
# finding the column labels of the data frame
df.columns

Index(['Event.Id', 'Investigation.Type', 'Accident.Number', 'Event.Date',
       'Location', 'Country', 'Latitude', 'Longitude', 'Airport.Code',
       'Airport.Name', 'Injury.Severity', 'Aircraft.damage',
       'Aircraft.Category', 'Registration.Number', 'Make', 'Model',
       'Amateur.Built', 'Number.of.Engines', 'Engine.Type', 'FAR.Description',
       'Schedule', 'Purpose.of.flight', 'Air.carrier', 'Total.Fatal.Injuries',
       'Total.Serious.Injuries', 'Total.Minor.Injuries', 'Total.Uninjured',
       'Weather.Condition', 'Broad.phase.of.flight', 'Report.Status',
       'Publication.Date'],
      dtype='object')

## Data Cleaning
**NOTE**;this is the most crucial and extensive part of our project;
**WHY** we will now begin carefully and slowly nitpicking our data because after having a general overview of the information
-We decide which information in **dataframe** actually helps= **adding value to our insights for future planning,increase overall productivity and allow for the highest quality information in your decision-making**
-the processes includes;{ **droping rows/columns,filling missing values,dealing with outliers,correcting errors,handling duplicates,data transformation,feature engineering and Data integration}**
-At the end of this we will have **"perfect_dataFrame"** which is of good data quality,from which we can depict graphs,has a good documentation & **is actually relevant and can provide keen and extensive insights**

In [8]:
#  return boolean series finding duplicated rows
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
90343    False
90344    False
90345    False
90346    False
90347    False
Length: 90348, dtype: bool

### finding overall % of missing values in columns 
this will help us establish which of the columns has the highest number of missing values and if whether they have an impact to our analysis.This processes will best decide which relevant/irrelevant columns **can be filled/dropped,imputated**

In [9]:
# finding missing in column(%)
df.isnull().mean()*100

Event.Id                   1.614867
Investigation.Type         0.000000
Accident.Number            1.614867
Event.Date                 1.614867
Location                   1.672422
Country                    1.865011
Latitude                  61.944924
Longitude                 61.954886
Airport.Code              44.382831
Airport.Name              41.570372
Injury.Severity            2.721698
Aircraft.damage            5.150086
Aircraft.Category         64.263736
Registration.Number        3.072564
Make                       1.684597
Model                      1.716695
Amateur.Built              1.727764
Number.of.Engines          8.348829
Engine.Type                9.447913
FAR.Description           64.555939
Schedule                  86.073848
Purpose.of.flight          8.468367
Air.carrier               81.573471
Total.Fatal.Injuries      14.233851
Total.Serious.Injuries    15.461327
Total.Minor.Injuries      14.822686
Total.Uninjured            8.158454
Weather.Condition          6.586753
Broad.phase.of.flight     31.681941
Report.Status              8.677558
Publication.Date          18.471909
dtype: float64

In [10]:
another_1=df.copy()

In [64]:
df = another_1.copy()

In [65]:
df.shape

(90348, 31)

In [66]:
# finalising the columns with missing values beyond 60% & their relevance
#dropping columns 
df.drop(columns = ["Schedule", "FAR.Description", "Longitude", "Latitude", "Location", "Air.carrier"], inplace=True)

In [67]:
# dropping columns{BASED ON RELEVANCE}
df.isnull().mean()*100

Event.Id                   1.614867
Investigation.Type         0.000000
Accident.Number            1.614867
Event.Date                 1.614867
Country                    1.865011
Airport.Code              44.382831
Airport.Name              41.570372
Injury.Severity            2.721698
Aircraft.damage            5.150086
Aircraft.Category         64.263736
Registration.Number        3.072564
Make                       1.684597
Model                      1.716695
Amateur.Built              1.727764
Number.of.Engines          8.348829
Engine.Type                9.447913
Purpose.of.flight          8.468367
Total.Fatal.Injuries      14.233851
Total.Serious.Injuries    15.461327
Total.Minor.Injuries      14.822686
Total.Uninjured            8.158454
Weather.Condition          6.586753
Broad.phase.of.flight     31.681941
Report.Status              8.677558
Publication.Date          18.471909
dtype: float64

In [68]:
# do not add actionable insights for analysis
df.drop(columns = ['Airport.Name'],inplace=True)

In [69]:
# final confirmation of relevant columns
df.isnull().mean()*100

Event.Id                   1.614867
Investigation.Type         0.000000
Accident.Number            1.614867
Event.Date                 1.614867
Country                    1.865011
Airport.Code              44.382831
Injury.Severity            2.721698
Aircraft.damage            5.150086
Aircraft.Category         64.263736
Registration.Number        3.072564
Make                       1.684597
Model                      1.716695
Amateur.Built              1.727764
Number.of.Engines          8.348829
Engine.Type                9.447913
Purpose.of.flight          8.468367
Total.Fatal.Injuries      14.233851
Total.Serious.Injuries    15.461327
Total.Minor.Injuries      14.822686
Total.Uninjured            8.158454
Weather.Condition          6.586753
Broad.phase.of.flight     31.681941
Report.Status              8.677558
Publication.Date          18.471909
dtype: float64

In [59]:
# summary of my cleaned data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90348 entries, 0 to 90347
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      90348 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Country                 88663 non-null  object
 5   Airport.Code            50249 non-null  object
 6   Injury.Severity         87889 non-null  object
 7   Aircraft.damage         85695 non-null  object
 8   Aircraft.Category       32287 non-null  object
 9   Registration.Number     87572 non-null  object
 10  Make                    88826 non-null  object
 11  Model                   88797 non-null  object
 12  Amateur.Built           88787 non-null  object
 13  Number.of.Engines       82805 non-null  float64
 14  Engine.Type             81812 non-null  object
 15  Purpose.of.flight       82697 non-null  object
 16  Total.Fatal.Injuries    77488 non-null  float64
 17  Total.Serious.Injuries  76379 non-null  float64
 18  Total.Minor.Injuries    76956 non-null  float64
 19  Total.Uninjured         82977 non-null  float64
 20  Weather.Condition       84397 non-null  object
 21  Broad.phase.of.flight   61724 non-null  object
 22  Report.Status           82508 non-null  object
 23  Publication.Date        73659 non-null  object
dtypes: float64(5), object(19)
memory usage: 16.5+ MB

In [70]:
# Gaining descriptive statistics from the data frame
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,82805.000000,77488.000000,76379.000000,76956.000000,82977.000000
mean,1.146585,0.647855,0.279881,0.357061,5.325440
std,0.446510,5.485960,1.544084,2.235625,27.913634
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,0.000000,0.000000,1.000000
75%,1.000000,0.000000,0.000000,0.000000,2.000000
max,8.000000,349.000000,161.000000,380.000000,699.000000

In [71]:
# dropping row with missing values only for object columns
df.dropna(subset = df.select_dtypes(include=['object']).columns,inplace=True)

In [72]:
df.shape

(3999, 24)

In [73]:
df.isnull().mean()*100

Event.Id                   0.000000
Investigation.Type         0.000000
Accident.Number            0.000000
Event.Date                 0.000000
Country                    0.000000
Airport.Code               0.000000
Injury.Severity            0.000000
Aircraft.damage            0.000000
Aircraft.Category          0.000000
Registration.Number        0.000000
Make                       0.000000
Model                      0.000000
Amateur.Built              0.000000
Number.of.Engines          0.125031
Engine.Type                0.000000
Purpose.of.flight          0.000000
Total.Fatal.Injuries      55.063766
Total.Serious.Injuries    53.913478
Total.Minor.Injuries      47.011753
Total.Uninjured           12.503126
Weather.Condition          0.000000
Broad.phase.of.flight      0.000000
Report.Status              0.000000
Publication.Date           0.000000
dtype: float64

## identifying&handling outliers
**Outliers**-data points that significantly differ from the rest of the dataset
in this step we to spot what are the features that do not add value to the continuos data.we do this by identifying outliers by using statistical methods in this case **{Interquartile range}**
**Treatment** we decide whether to remove, cap or transform outliers

In [74]:
#identifying outliers in our continuos data
Q1 = df['Total.Fatal.Injuries'].quantile(0.25)
Q3 = df['Total.Fatal.Injuries'].quantile(0.75)
IQR = Q3 - Q1
outliers = df[(df['Total.Fatal.Injuries'] < (Q1 - 1.5 * IQR)) | (df['Total.Fatal.Injuries'] > (Q3 + 1.5 * IQR))]
outliers

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Country,Airport.Code,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
13,20020917X02134,Accident,FTW82FRA14,1982-01-02,United States,T72,Fatal(1),Destroyed,Airplane,N758SK,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Takeoff,Probable Cause,02-01-1983
26,20020917X01720,Accident,ATL82FA033,1982-01-03,United States,SOP,Fatal(1),Destroyed,Airplane,N10VS,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,03-01-1983
37,20020917X02304,Accident,LAX82FUM06,1982-01-05,United States,L39,Fatal(3),Destroyed,Airplane,N4520K,...,Reciprocating,Business,3.0,0.0,0.0,0.0,IMC,Cruise,Probable Cause,05-01-1983
54,20020917X02414,Accident,MIA82FLD14,1982-01-08,United States,X41,Fatal(1),Destroyed,Airplane,N80264,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,08-01-1983
55,20020917X01881,Accident,CHI82FA024,1982-01-08,United States,PHO,Fatal(1),Destroyed,Airplane,N207CB,...,Reciprocating,Personal,1.0,1.0,0.0,0.0,VMC,Approach,Probable Cause,08-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63828,20071219X01978,Accident,SEA08FA042,2007-12-10,United States,KSMN,Fatal(2),Destroyed,Airplane,N925TT,...,Turbo Prop,Executive/corporate,2.0,NaN,NaN,2.0,IMC,Takeoff,Probable Cause,04-08-2011
63833,20071227X01998,Accident,NYC08LA059,2007-12-12,United States,SVH,Fatal(1),Substantial,Airplane,N199JW,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,VMC,Takeoff,Probable Cause,14-01-2009
63871,20080102X00007,Accident,CHI08FA053,2007-12-20,United States,KSPI,Fatal(3),Destroyed,Airplane,N17784,...,Reciprocating,Personal,3.0,NaN,NaN,NaN,IMC,Approach,Probable Cause,10-05-2010
63899,20080108X00030,Accident,CHI08FA055,2007-12-27,United States,TVC,Fatal(1),Destroyed,Airplane,N37249,...,Reciprocating,Personal,1.0,1.0,NaN,NaN,IMC,Approach,Probable Cause,05-08-2011
63909,20080114X00045,Accident,LAX08FA043,2007-12-30,United States,PRB,Fatal(1),Substantial,Airplane,N254SR,...,Reciprocating,Personal,1.0,NaN,NaN,NaN,VMC,Maneuvering,Probable Cause,20-06-2014

In [75]:
Q1 = df['Number.of.Engines'].quantile(0.25)
Q3 = df['Number.of.Engines'].quantile(0.75)
IQR = Q3 - Q1
outliers_1 = df[(df['Number.of.Engines'] < (Q1 - 1.5 * IQR)) | (df['Number.of.Engines'] > (Q3 + 1.5 * IQR))]
outliers_1

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Country,Airport.Code,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
8,20020909X01561,Accident,NYC82DA015,1982-01-01,United States,N58,Non-Fatal,Substantial,Airplane,N7967Q,...,Reciprocating,Business,0.0,0.0,0.0,2.0,IMC,Landing,Probable Cause,01-01-1982
26,20020917X01720,Accident,ATL82FA033,1982-01-03,United States,SOP,Fatal(1),Destroyed,Airplane,N10VS,...,Reciprocating,Personal,1.0,0.0,0.0,0.0,IMC,Approach,Probable Cause,03-01-1983
45,20020917X02423,Accident,MKC82DA016,1982-01-06,United States,K07,Non-Fatal,Substantial,Airplane,N2672A,...,Reciprocating,Executive/corporate,0.0,0.0,0.0,3.0,VMC,Approach,Probable Cause,06-01-1983
53,20020917X02141,Accident,FTW82FRG20,1982-01-07,United States,LRD,Non-Fatal,Substantial,Airplane,N1698M,...,Reciprocating,Unknown,0.0,0.0,0.0,3.0,VMC,Standing,Probable Cause,07-01-1983
65,20020917X01994,Accident,FTW82DA038,1982-01-09,United States,DWH,Non-Fatal,Substantial,Airplane,N55489,...,Reciprocating,Personal,0.0,0.0,0.0,3.0,VMC,Taxi,Probable Cause,09-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63834,20080123X00097,Accident,NYC08CA073,2007-12-12,United States,MLS,Non-Fatal,Substantial,Airplane,N112ED,...,Turbo Prop,Personal,NaN,NaN,NaN,2.0,VMC,Landing,Probable Cause,17-06-2019
63836,20080123X00094,Accident,NYC08CA072,2007-12-13,United States,LNS,Non-Fatal,Substantial,Airplane,N777EV,...,Reciprocating,Personal,NaN,NaN,NaN,1.0,VMC,Approach,Probable Cause,28-02-2008
63841,20080213X00187,Accident,NYC08LA062B,2007-12-14,United States,JFK,Non-Fatal,Substantial,Airplane,N184JB,...,Turbo Fan,Positioning,NaN,NaN,NaN,5.0,IMC,Standing,Probable Cause,30-09-2009
63862,20080312X00298,Accident,MIA08CA046,2007-12-19,United States,KAGC,Non-Fatal,Substantial,Airplane,N13616,...,Turbo Jet,Ferry,NaN,NaN,NaN,2.0,VMC,Cruise,Probable Cause,31-03-2008
63899,20080108X00030,Accident,CHI08FA055,2007-12-27,United States,TVC,Fatal(1),Destroyed,Airplane,N37249,...,Reciprocating,Personal,1.0,1.0,NaN,NaN,IMC,Approach,Probable Cause,05-08-2011

In [76]:
Q1 = df['Total.Serious.Injuries'].quantile(0.25)
Q3 = df['Total.Serious.Injuries'].quantile(0.75)
IQR = Q3 - Q1
outliers_2 = df[(df['Total.Serious.Injuries'] < (Q1 - 1.5 * IQR)) | (df['Total.Serious.Injuries'] > (Q3 + 1.5 * IQR))]
outliers_2

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Country,Airport.Code,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
44,20020917X01651,Accident,ANC82FA012,1982-01-05,United States,BET,Non-Fatal,Substantial,Airplane,N3343S,...,Reciprocating,Unknown,0.0,2.0,0.0,0.0,VMC,Takeoff,Probable Cause,05-01-1983
55,20020917X01881,Accident,CHI82FA024,1982-01-08,United States,PHO,Fatal(1),Destroyed,Airplane,N207CB,...,Reciprocating,Personal,1.0,1.0,0.0,0.0,VMC,Approach,Probable Cause,08-01-1983
82,20020917X02111,Accident,FTW82FPA10,1982-01-12,United States,11,Non-Fatal,Substantial,Airplane,N8678M,...,Reciprocating,Personal,0.0,1.0,0.0,1.0,IMC,Descent,Probable Cause,12-01-1983
93,20020917X02538,Accident,NYC82FA021,1982-01-15,United States,JFK,Non-Fatal,Substantial,Airplane,N341PL,...,Turbo Prop,Unknown,0.0,1.0,2.0,12.0,VMC,Takeoff,Probable Cause,15-01-1983
141,20020917X02295,Accident,LAX82FUJ25,1982-01-21,United States,E51,Non-Fatal,Destroyed,Airplane,N40291,...,Reciprocating,Executive/corporate,0.0,1.0,2.0,0.0,IMC,Maneuvering,Probable Cause,21-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63776,20071130X01879,Accident,DFW08FA038,2007-11-27,United States,KRVS,Fatal(2),Destroyed,Airplane,N3NG,...,Reciprocating,Personal,2.0,1.0,0.0,0.0,VMC,Climb,Probable Cause,28-12-2008
63777,20080109X00035,Accident,NYC08CA048,2007-11-28,United States,LBE,Non-Fatal,Substantial,Airplane,N103JT,...,Reciprocating,Personal,NaN,1.0,NaN,NaN,VMC,Landing,Probable Cause,31-03-2008
63806,20080122X00089,Accident,CHI08CA020,2007-12-05,United States,0IN1,Non-Fatal,Substantial,Helicopter,N75068,...,Reciprocating,Personal,NaN,1.0,NaN,NaN,VMC,Landing,Probable Cause,28-02-2008
63847,20071226X01986,Accident,DEN08LA041,2007-12-15,United States,PHG,Non-Fatal,Destroyed,Airplane,N63LH,...,Reciprocating,Personal,0.0,1.0,1.0,0.0,VMC,Cruise,Probable Cause,24-12-2008
63899,20080108X00030,Accident,CHI08FA055,2007-12-27,United States,TVC,Fatal(1),Destroyed,Airplane,N37249,...,Reciprocating,Personal,1.0,1.0,NaN,NaN,IMC,Approach,Probable Cause,05-08-2011

In [32]:
Q1 = df['Total.Minor.Injuries'].quantile(0.25)
Q3 = df['Total.Minor.Injuries'].quantile(0.75)
IQR = Q3 - Q1
outliers_3 = df[(df['Total.Minor.Injuries'] < (Q1 - 1.5 * IQR)) | (df['Total.Minor.Injuries'] > (Q3 + 1.5 * IQR))]
outliers_3

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Country,Airport.Code,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
5,20170710X52551,Accident,NYC79AA106,1979-09-17,United States,NaN,Non-Fatal,Substantial,Airplane,CF-TLU,...,Turbo Fan,NaN,NaN,NaN,1.0,44.0,VMC,Climb,Probable Cause,19-09-2017
9,20020909X01560,Accident,MIA82DA029,1982-01-01,United States,JAX,Non-Fatal,Substantial,NaN,N3906K,...,Reciprocating,Personal,0.0,0.0,3.0,0.0,IMC,Cruise,Probable Cause,01-01-1982
12,20020917X02148,Accident,FTW82FRJ07,1982-01-02,United States,NaN,Non-Fatal,Destroyed,Airplane,N14779,...,Reciprocating,Personal,0.0,0.0,1.0,0.0,IMC,Cruise,Probable Cause,02-01-1983
28,20020917X02340,Accident,MIA82DA030,1982-01-03,United States,NaN,Non-Fatal,Substantial,Airplane,N94252,...,Reciprocating,Personal,0.0,0.0,1.0,1.0,VMC,Descent,Probable Cause,03-01-1983
29,20020917X02155,Accident,LAX82DA035,1982-01-03,United States,NaN,Non-Fatal,Substantial,Airplane,N8630V,...,Reciprocating,Personal,0.0,0.0,2.0,0.0,VMC,Maneuvering,Probable Cause,03-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90297,20221203106405,Accident,ERA23FA077,2022-12-02,United States,5B6,Fatal,Substantial,Airplane,N3515H,...,NaN,Personal,1.0,0.0,1.0,0.0,VMC,NaN,NaN,20-12-2022
90314,20221212106439,Accident,DCA23LA093,2022-12-08,United States,NaN,Serious,NaN,NaN,N649UA,...,NaN,NaN,0.0,3.0,1.0,175.0,NaN,NaN,NaN,12-12-2022
90325,20221213106448,Accident,CEN23LA062,2022-12-12,United States,NaN,Serious,NaN,NaN,N231GZ,...,NaN,Personal,0.0,0.0,2.0,0.0,NaN,NaN,NaN,15-12-2022
90331,20221214106459,Accident,GAA23WA042,2022-12-14,Canada,NaN,Serious,NaN,NaN,N5EQ,...,NaN,NaN,0.0,0.0,2.0,0.0,NaN,NaN,NaN,20-12-2022
90334,20221219106474,Accident,ANC23LA009,2022-12-15,United States,NaN,Serious,NaN,NaN,N991AB,...,NaN,NaN,0.0,1.0,1.0,0.0,NaN,NaN,NaN,22-12-2022

In [77]:
Q1 = df['Total.Uninjured'].quantile(0.25)
Q3 = df['Total.Uninjured'].quantile(0.75)
IQR = Q3 - Q1
outliers_4 = df[(df['Total.Uninjured'] < (Q1 - 1.5 * IQR)) | (df['Total.Uninjured'] > (Q3 + 1.5 * IQR))]
outliers_4

,Event.Id,Investigation.Type,Accident.Number,Event.Date,Country,Airport.Code,Injury.Severity,Aircraft.damage,Aircraft.Category,Registration.Number,...,Engine.Type,Purpose.of.flight,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured,Weather.Condition,Broad.phase.of.flight,Report.Status,Publication.Date
46,20020917X02157,Accident,LAX82DA039,1982-01-06,United States,MMH,Non-Fatal,Substantial,Helicopter,N608RA,...,Turbo Shaft,Business,0.0,0.0,0.0,6.0,VMC,Taxi,Probable Cause,06-01-1983
69,20020917X02158,Accident,LAX82DA041,1982-01-10,United States,P06,Non-Fatal,Destroyed,Airplane,N2753J,...,Reciprocating,Personal,0.0,0.0,0.0,4.0,VMC,Landing,Probable Cause,10-01-1983
86,20020917X01996,Accident,FTW82DA040,1982-01-13,United States,HOB,Non-Fatal,Substantial,Airplane,N2396W,...,Reciprocating,Personal,0.0,0.0,0.0,4.0,VMC,Takeoff,Probable Cause,13-01-1983
93,20020917X02538,Accident,NYC82FA021,1982-01-15,United States,JFK,Non-Fatal,Substantial,Airplane,N341PL,...,Turbo Prop,Unknown,0.0,1.0,2.0,12.0,VMC,Takeoff,Probable Cause,15-01-1983
129,20020917X02397,Accident,MIA82FA034,1982-01-19,United States,MIA,Non-Fatal,Substantial,Airplane,HCBHS,...,Turbo Prop,Unknown,0.0,0.0,0.0,6.0,VMC,Landing,Probable Cause,19-01-1983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63747,20071207X01914,Accident,MIA08CA018,2007-11-18,United States,KM93,Non-Fatal,Substantial,Airplane,N5803A,...,Reciprocating,Personal,NaN,NaN,NaN,4.0,VMC,Landing,Probable Cause,20-12-2007
63796,20071206X01909,Accident,SEA08LA041,2007-12-02,United States,COE,Non-Fatal,Substantial,Airplane,N551GF,...,Turbo Fan,Personal,NaN,NaN,NaN,8.0,VMC,Landing,Probable Cause,24-03-2010
63841,20080213X00187,Accident,NYC08LA062B,2007-12-14,United States,JFK,Non-Fatal,Substantial,Airplane,N184JB,...,Turbo Fan,Positioning,NaN,NaN,NaN,5.0,IMC,Standing,Probable Cause,30-09-2009
63877,20080124X00101,Accident,NYC08CA068,2007-12-22,United States,NH15,Non-Fatal,Substantial,Airplane,N3070A,...,Reciprocating,Personal,NaN,NaN,NaN,4.0,VMC,Maneuvering,Probable Cause,28-02-2008
63896,20071231X02008,Incident,DEN08IA044,2007-12-26,United States,ASE,Incident,Minor,Airplane,N47BC,...,Reciprocating,Personal,0.0,0.0,0.0,4.0,VMC,Climb,Probable Cause,24-12-2008

## Handling missing values 
-some of the data present might have missing values 
-it is upto us to find the best mode of **imputation-missing data is filled in to create a complete data matrix that can be analysed using standard methods**
-imputation can be done through-**mean,median,mode**
-This is done so as to enable us keep our original data & key points to calculate keen insights that help in focusing on our objective

In [81]:
# filling missing values of continuos data
relevant_columns = ["Number.of.Engines", "Total.Fatal.Injuries", "Total.Serious.Injuries", "Total.Minor.Injuries", "Total.Uninjured"]
relevant_columns

['Number.of.Engines',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured']

In [82]:
# assigned list of columns and re_assigning missing values with their median
df[relevant_columns] = df[relevant_columns].fillna(df[relevant_columns].median())

In [83]:
#descriptive statistics of **cleaned dataFrame**
df.describe()

,Number.of.Engines,Total.Fatal.Injuries,Total.Serious.Injuries,Total.Minor.Injuries,Total.Uninjured
count,3999.000000,3999.000000,3999.000000,3999.00000,3999.000000
mean,1.135034,0.226307,0.110278,0.27932,2.663916
std,0.386452,3.717655,0.616670,1.15517,17.202312
min,0.000000,0.000000,0.000000,0.00000,0.000000
25%,1.000000,0.000000,0.000000,0.00000,1.000000
50%,1.000000,0.000000,0.000000,0.00000,1.000000
75%,1.000000,0.000000,0.000000,0.00000,2.000000
max,4.000000,228.000000,26.000000,42.00000,588.000000

In [84]:
# Confirmation of final missing values in both categorical and continuos data
df.isnull().sum()

Event.Id                  0
Investigation.Type        0
Accident.Number           0
Event.Date                0
Country                   0
Airport.Code              0
Injury.Severity           0
Aircraft.damage           0
Aircraft.Category         0
Registration.Number       0
Make                      0
Model                     0
Amateur.Built             0
Number.of.Engines         0
Engine.Type               0
Purpose.of.flight         0
Total.Fatal.Injuries      0
Total.Serious.Injuries    0
Total.Minor.Injuries      0
Total.Uninjured           0
Weather.Condition         0
Broad.phase.of.flight     0
Report.Status             0
Publication.Date          0
dtype: int64